### konfiguracja mysql ###
db_host: "host" #np. titanaxe: 54.38.50.59
db_port: 3306 #port np. 3306
db_name: "www6969_testowa_baza" #nazwa bazy danych
db_user: "www6969_testowa_baza" #użytkownik bazy danych
db_table: "whitelist_users" #nazwa tabeli, daj jaką chcesz bo plugin i tak utworzy
db_password: "123" #hasło do bazy danych

### konfiguracja pluginu ###

## Zmienne:
## {ADMIN}
## {PLAYER}

wl-kick-message: "&8» &eBV&8-&fWHITELIST &8«\n\n&c✖ &7Mam problem ze wzrokiem lub nie ma cię na whiteliście (⌐■_■) &c✖\n\n&cW sprawach biznesowych napisz na discordzie:\n&8– &7barthvisuals#7981\n&8– &7nolemretaW#2137"
wl-command-error: "&cNie ma takiej komendy!"
wl-command-add: "&aDodano gracza: {PLAYER} do whitelisty!"
wl-command-remove: "&cUsunięto gracza {PLAYER} z whitelisty!"
wl-command-nopermissions: "&cNie masz permisji (whitelist.all)!"
wl-add-log-message: "&a{ADMIN} dodał do whitelisty gracza: {PLAYER}!"
wl-remove-log-message: "&c{ADMIN} usunął z whitelisty gracza: {PLAYER}!"